# -*- coding: utf-8 -*-
{
    'name': 'Laundry Base',
    'name_ar': 'نظام المغسلة - الأساس',
    'version': '17.0.1.1.0',
    'category': 'Point of Sale',
    'summary': 'Core models for Laundry POS Operations - Farha Laundry',
    'author': 'TelNova Solutions',
    'website': 'https://telnovasolution.com',
    'license': 'LGPL-3',
    'icon': 'static/description/icon.png',
    'depends': ['point_of_sale', 'account', 'mail', 'base'],
    'data': [
        'security/laundry_groups.xml',
        'security/ir.model.access.csv',
        'security/laundry_record_rules.xml',
        'data/laundry_sequence_data.xml',
        'data/laundry_stage_data.xml',
        'data/laundry_item_category_data.xml',
        'data/laundry_service_type_data.xml',
        'wizard/laundry_billing_wizard_views.xml',
        'views/laundry_branch_views.xml',
        'views/laundry_stage_views.xml',
        'views/laundry_item_category_views.xml',
        'views/laundry_service_type_views.xml',
        'views/laundry_commercial_account_views.xml',
        'views/laundry_order_views.xml',
        'views/laundry_issue_views.xml',
        'views/laundry_audit_log_views.xml',
        'views/laundry_menus.xml',
        'data/laundry_loyalty_data.xml',
        'views/laundry_loyalty_views.xml',
        'views/laundry_hotel_views.xml',
        'views/laundry_barcode_scan_views.xml',
        'report/laundry_hotel_manifest.xml',
        'report/laundry_z_report.xml',
        'report/laundry_label_report.xml',
        'report/laundry_receipt_report.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
