{
    "name": "POS Laundry Receipt",
    "version": "17.0.1.6.5",
    "summary": "Laundry intake, order tracking, and durable label print queue",
    "category": "Point of Sale",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["point_of_sale", "pos_epson_printer", "account", "web", "contacts", "base_setup", "resource", "muk_web_appsbar"],
    "data": [
        "security/pos_order_tracking_security.xml",
        "security/ir.model.access.csv",
        "data/laundry_sequence.xml",
        "data/laundry_sla_calendar.xml",
        "data/pos_bilingual_names.xml",
        "data/accounting_menu_name.xml",
        "report/pos_laundry_receipt_report.xml",
        "report/laundry_tracking_label_report.xml",

        "views/laundry_intake_views.xml",
        "views/pos_order_tracking_views.xml",
        "views/laundry_label_views.xml",
        "views/account_move_inherit_views.xml",
        "views/res_config_settings_views.xml",
        "views/pos_order_inherit_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pos_laundry_receipt/static/lib/html5-qrcode/html5-qrcode.min.js",
            "point_of_sale/static/src/app/utils/html-to-image.js",
            "pos_laundry_receipt/static/src/js/laundry_label_direct_print.js",
            "pos_laundry_receipt/static/src/js/laundry_tracking_dashboard.js",
            "pos_laundry_receipt/static/src/js/laundry_sla_performance_dashboard.js",
            "pos_laundry_receipt/static/src/js/sidebar_collapse.js",
            "pos_laundry_receipt/static/src/xml/laundry_tracking_dashboard.xml",
            "pos_laundry_receipt/static/src/xml/laundry_sla_performance_dashboard.xml",
            "pos_laundry_receipt/static/src/scss/laundry_tracking_backend.scss",
            "pos_laundry_receipt/static/src/scss/laundry_print_overlay.scss",
            "pos_laundry_receipt/static/src/scss/laundry_receipt.scss",
        ],
       "point_of_sale._assets_pos": [
            "pos_laundry_receipt/static/lib/html5-qrcode/html5-qrcode.min.js",
            "pos_laundry_receipt/static/src/js/laundry_pos_assets_watchdog.js",
            "pos_laundry_receipt/static/src/js/laundry_label_direct_print.js",
            "pos_laundry_receipt/static/src/js/laundry_receipt_button.js",
            "pos_laundry_receipt/static/src/js/laundry_order_tracking_button.js",

            "pos_laundry_receipt/static/src/js/new_order_button.js",

            "pos_laundry_receipt/static/src/xml/laundry_receipt_templates.xml",
            "pos_laundry_receipt/static/src/scss/laundry_pos_design_system.scss",
            "pos_laundry_receipt/static/src/scss/laundry_print_overlay.scss",
            "pos_laundry_receipt/static/src/scss/laundry_receipt.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
