# -*- coding: utf-8 -*-
"""Generated by tools/import_price_book.py -- do not edit by hand.

Source: /opt/odoo17/كشف اسعار مفصل بالعماء 1.xlsx
Generated: 2026-08-06 01:57:25 UTC

PRODUCTS is (code, arabic_name, english_name, {tier: price}).  ``code``
becomes ``default_code`` on the product and is the key the sync matches on, so
re-running the import updates rather than duplicates.

SHEET_CUSTOMERS is the customer list exactly as the sheet spells it, kept for
traceability; the mapping onto real partners lives in models/hotel_setup.py.
"""

TIERS = ['base', 'fann', 'naseem', 'lulua']

PRODUCTS = [
    ('HTL-01', 'شرشف سرير كبير', 'Large Bed Sheet', {'base': 2.9, 'fann': 2.5, 'lulua': 2.75, 'naseem': 2.85}),
    ('HTL-02', 'شرشف سرير صغير', 'Small Bed Sheet', {'base': 1.9, 'fann': 1.5, 'lulua': 1.75, 'naseem': 1.85}),
    ('HTL-03', 'غطاء سرير كبير', 'Large Duvet Cover', {'base': 2.9, 'fann': 2.5, 'lulua': 2.75, 'naseem': 2.85}),
    ('HTL-04', 'غطاء سرير صغير', 'Small Duvet Cover', {'base': 1.9, 'fann': 1.5, 'lulua': 1.75, 'naseem': 1.85}),
    ('HTL-05', 'غطاء سرير عازل للماء كبير', 'Large Waterproof Mattress Protector', {'base': 2.9, 'fann': 2.5, 'lulua': 2.75, 'naseem': 2.85}),
    ('HTL-06', 'غطاء سرير عازل للماء صغير', 'Small Waterproof Mattress Protector', {'base': 1.9, 'fann': 1.5, 'lulua': 1.75, 'naseem': 1.85}),
    ('HTL-07', 'لحاف كبير', 'Large Duvet', {'base': 4.15, 'fann': 3.5, 'lulua': 4.0, 'naseem': 4.1}),
    ('HTL-08', 'لحاف صغير', 'Small Duvet', {'base': 3.15, 'fann': 2.75, 'lulua': 3.0, 'naseem': 3.1}),
    ('HTL-09', 'بطانية', 'Blanket', {'base': 5.15, 'fann': 4.75, 'lulua': 5.0, 'naseem': 5.1}),
    ('HTL-10', 'مخدة', 'Pillow', {'base': 2.65, 'fann': 2.0, 'lulua': 2.5, 'naseem': 2.5}),
    ('HTL-11', 'كيس مخدة', 'Pillowcase', {'base': 0.9, 'fann': 0.5, 'lulua': 0.75, 'naseem': 0.85}),
    ('HTL-12', 'منشفة كبير (جسم)', 'Large Towel (Body)', {'base': 1.4, 'fann': 1.25, 'lulua': 1.25, 'naseem': 1.35}),
    ('HTL-13', 'منشفة وسط (يد)', 'Medium Towel (Hand)', {'base': 1.4, 'fann': 1.25, 'lulua': 1.25, 'naseem': 1.35}),
    ('HTL-14', 'منشفة صغير(وجه)', 'Small Towel (Face)', {'base': 1.4, 'fann': 1.25, 'lulua': 1.25, 'naseem': 1.35}),
    ('HTL-15', 'دواسة', 'Bath Mat', {'base': 0.65, 'fann': 0.5, 'lulua': 0.5, 'naseem': 0.6}),
    ('HTL-16', 'منشفة روب', 'Bathrobe', {'base': 3.15, 'fann': 3.0, 'lulua': 3.0, 'naseem': 3.1}),
    ('HTL-17', 'حلية للسرير كبير', 'Large Bed Valance', {'base': 0.65, 'fann': 0.5, 'lulua': 0.5, 'naseem': 0.5}),
    ('HTL-18', 'حلية للسرير صغير', 'Small Bed Valance', {'base': 0.65, 'fann': 0.5, 'lulua': 0.5, 'naseem': 0.5}),
    ('HTL-19', 'غطاء كرسي', 'Chair Cover', {'base': 1.65, 'fann': 1.5, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-20', 'مفرش طاولة كبير', 'Large Tablecloth', {'base': 2.15, 'fann': 2.0, 'lulua': 2.0, 'naseem': 2.1}),
    ('HTL-21', 'مفرش طاولة صغير', 'Small Tablecloth', {'base': 2.15, 'fann': 2.0, 'lulua': 2.0, 'naseem': 2.1}),
    ('HTL-22', 'منديل طعام', 'Napkin', {'base': 0.65, 'fann': 0.5, 'lulua': 0.5, 'naseem': 0.6}),
    ('HTL-23', 'ديكور طاولة', 'Table Runner', {'base': 0.15, 'fann': 0.0, 'lulua': 0.0, 'naseem': 0.1}),
    ('HTL-24', 'حلية طاولة', 'Table Skirt', {'base': 0.15, 'fann': 0.0, 'lulua': 0.0, 'naseem': 0.1}),
    ('HTL-25', 'قميص', 'Shirt', {'base': 1.65, 'fann': 1.0, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-26', 'بنطلون', 'Trousers', {'base': 1.65, 'fann': 1.0, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-27', 'صديري', 'Vest', {'base': 1.65, 'fann': 1.0, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-28', 'تي شيرت', 'T-Shirt', {'base': 1.65, 'fann': 1.0, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-29', 'جاكيت', 'Jacket', {'base': 1.65, 'fann': 1.0, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-30', 'جاكيت مطبخ', 'Chef Jacket', {'base': 1.65, 'fann': 1.0, 'lulua': 1.5, 'naseem': 1.6}),
    ('HTL-31', 'فستان', 'Dress', {'base': 0.15, 'fann': 0.0, 'lulua': 0.0, 'naseem': 0.1}),
    ('HTL-32', 'ستارة شيفون', 'Chiffon Curtain (per m)', {'base': 3.15, 'fann': 2.0, 'lulua': 3.0, 'naseem': 3.1}),
    ('HTL-33', 'ستارة عازل', 'Blackout Curtain (per m)', {'base': 3.15, 'fann': 2.0, 'lulua': 3.0, 'naseem': 3.1}),
    ('HTL-34', 'ستارة قماش', 'Fabric Curtain (per m)', {'base': 3.15, 'fann': 2.0, 'lulua': 3.0, 'naseem': 3.1}),
    ('HTL-35', 'سجادة صلاة', 'Prayer Rug', {'base': 0.0, 'fann': 0.0, 'lulua': 0.0, 'naseem': 0.0}),
    ('HTL-36', 'بدلة كاملة ( ثلاث قطع )', 'Full Suit (3 Pieces)', {'base': 3.15, 'fann': 2.0, 'lulua': 2.0, 'naseem': 3.1}),
]

SHEET_CUSTOMERS = [
    ('base', 'مجموعة ابداع الخليج العقارية ( كوخ 1)'),
    ('base', 'مجموعة ابداع الخليج العقارية (كوخ 2)'),
    ('base', 'مجموعة ابداع الخليج العقارية( كوخ 4)'),
    ('base', 'مجموعة ابداع الخليج العقارية (طيبة)'),
    ('base', 'شقق السمحة'),
    ('base', 'شقق اجنحة المنزل'),
    ('base', 'شقق سعيد العمري'),
    ('base', 'شقق قصر بوني'),
    ('base', 'شقق سليم'),
    ('base', 'شقق سحاب'),
    ('base', 'شاطي جيمي'),
    ('fann', 'شقق فنن سويت'),
    ('naseem', 'مؤسسة محمد سالم علي الغامدي الفندقية (النسمه الهادي )'),
    ('lulua', 'شقق لؤلؤة الحمدانية'),
]
