from . import laundry_intake
from . import pos_order
from . import laundry_label
from . import ir_actions_report
from . import ir_attachment
from . import pos_config
from . import pos_session
from . import res_config_settings
from . import res_partner
from . import account_move
